name: default
channels:
- conda-forge
- nodefaults
dependencies:
- python *
- tectonic ==0.15.0
- pip
- pip:
  - streamlit==1.45.1
  - openai==1.82.1
  - google-generativeai==0.8.5
  - pdfminer-six>=20250506, <20250507
  - jinja2==3.1.6
  - python-docx==1.1.2
  - docx2txt==0.9
  - stqdm==0.0.5
  - streamlit-ext==0.1.15
